name: LabCI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Build:
    strategy:
      matrix:
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check .zshrc
      run: touch ~/.zshrc && cat ~/.zshrc
    - uses: actions/checkout@v2
    - name: Initialize submodules
      run: git submodule update --recursive --init
    - name: Set up .zshrc variables
      run: |
        pwd
        pwd
        echo "tmp $(pwd)"
        echo "export TVM_HOME=$(pwd)" > ~/.zshrc
        echo "export PYTHONPATH=$TVM_HOME/python:${PYTHONPATH}" > ~/.zshrc
        cat ~/.zshrc
    - name: Build from source
      run: |
        mkdir build
        cp cmake/config.cmake build
        cd build
        cmake ..
        make -j12
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: tvm-build
        channel-priority: strict
        environment-file: conda/build-environment.yaml
        auto-activate-base: false
        use-only-tar-bz2: true
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Test@MacOS
      if: startsWith(matrix.os, 'macOS')
      shell: bash -l {0}
      run: >-
        conda activate tvm-build &&
        python -m pytest -v tests/python/contrib/test_bnns/test_onnx_topologies.py
