name: LabCI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: self-hosted
    env:
      TVM_HOME: /Users/octoml/actions-runner/_work/tvm/tvm
      #RUNNER_HOME: /Users/octoml/actions-runner/_work/tvm
      VENVS_HOME: /Users/octoml/actions-runner/_work/tvm/venvs
      TMP: a-${{ github.runner.workspace }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Initialize submodules
      run: git submodule update --recursive --init
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${WORKSPACE}
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Create venv
      run: |
        mkdir ${VENVS_HOME}
        cd ${VENVS_HOME}
        python3 -m venv tvm-build
        source tvm-build/bin/activate
        pip install -r ${TVM_HOME}/python/requirements.txt

    - name: Build TVM from source
      run: |
        CMAKE_FLAGS="-DUSE_LLVM=ON -DUSE_BNNS=ON"

        mkdir build
        cd build
        cmake .. $(echo $CMAKE_FLAGS)
        make -j8

    - name: Test@ONNX_MacOS
      run: |
        export PYTHONPATH=${TVM_HOME}/python:${PYTHONPATH}
        source ${VENVS_HOME}/tvm-build/bin/activate
        python -m pytest -v tests/python/contrib/test_bnns/test_onnx_topologies.py
    
    - name: Clean VENV
      if: always()
      run: rm -rf ${VENVS_HOME}
