name: LabCI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Build:
    strategy:
      matrix:
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check .zshrc
      run: touch ~/.zshrc && cat ~/.zshrc
    - uses: actions/checkout@v2
    - name: Initialize submodules
      run: git submodule update --recursive --init
    - name: Set up .zshrc variables
      run: |
        echo "export TVM_HOME=$(pwd)" >> ~/.zshrc
        echo "export PYTHONPATH=$(pwd)/python:${PYTHONPATH}" >> ~/.zshrc
        cat ~/.zshrc
    
    # - name: Test artifact
    #   run: |
    #     mkdir -p tmp_artifact
    #     echo hello > tmp_artifact/world.txt
    #     ls
    #     zip "tmp_artifact/world.zip" tmp_artifact/world.txt
    #     ls
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: my-artifact
    #     path: tmp_artifact/world.zip

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: octoml_nn_lab.yml
        workflow_conclusion: success
        name: my-artifact

    - name: Build from source
      run: |
        mkdir build
        cp cmake/config.cmake build
        cd build
        cmake ..
        make -j12
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: tvm-build
        channel-priority: strict
        environment-file: conda/build-environment.yaml
        auto-activate-base: false
        use-only-tar-bz2: true
    - name: Conda info
      run: |
        conda info
        conda list

    - name: Test tvm
      run: |
        source ~/.zshrc
        python -c "import tvm"
    
    - name: Test@MacOS
      if: startsWith(matrix.os, 'macOS')
      shell: bash -l {0}
      run: >-
        source ~/.zshrc &&
        conda activate tvm-build &&
        python -m pytest -v tests/python/contrib/test_bnns/test_onnx_topologies.py
